services:
  dns-gateway:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: ubdns-simple
    ports:
      - "8080:8080"
    environment:
      - PYTHON_VERSION=3.11
      - PORT=8080
      - ENABLE_NO_LOG=true
      - ADMIN_PASSWORD=726268
      - ENABLE_CLOUDFLARE_TUNNEL=true
      - CLOUDFLARE_TUNNEL_TOKEN=eyJhIjoiN2Y0MDU5OTFhNzE4ZjZhOWYxYWMwNjMyOTc3Yzg2ODAiLCJ0IjoiMTM1ODQyNmItMTc2YS00YzczLTkxNmItN2U0YjFmYTFiYjE3IiwicyI6Ik1XUXdZelkwWmpFdFlqVXdaUzAwTnpSaUxXRTVPRGt0TTJJME16WmxNbVUwT0RFNCJ9.eyJpc3MiOiJjYSIsImtpZCI6ImM2Y0MDU5OTFhNzE4ZjZhOWYxYWMwNjMyOTc3Yzg2ODAiLCJhdWQiOiJjYSIsImNpZCI6IjE3NDU3NjQ1NjR9.eyJpc3MiOiJjYSIsImtpZCI6ImM2Y0MDU5OTFhNzE0ZjZhOWYxYWMwNjMyOTc3Yzg2ODAiLCJhdWQiOiJjYSIsImNpZCI6IjE3NDU3NjQ1NjR9
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
