services:
  dns-gateway:
    build:
      context: .
      dockerfile: Dockerfile.simple
    cap_add:
    - NET_ADMIN
    container_name: ubdns-simple
    environment:
    - PYTHON_VERSION=3.11
    - PORT=8080
    - ENABLE_NO_LOG=true
    - ADMIN_PASSWORD=726268
    - ENABLE_CLOUDFLARE_TUNNEL=true
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./data:/app/data
version: '3.8'
